const header=document.querySelector('[data-header]');const menuButton=document.querySelector('.menu-button');const mobileMenu=document.querySelector('.mobile-menu');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>40),{passive:true});
menuButton.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuButton.setAttribute('aria-expanded',open);mobileMenu.setAttribute('aria-hidden',!open)});
mobileMenu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');mobileMenu.setAttribute('aria-hidden','true')}));
const footerObserverTarget=document.querySelector('.footer');
const footer=document.querySelector('.footer');if(footer){footer.innerHTML=`<div class="footer-renewed"><div class="footer-group"><div class="footer-brand">ROSE HIP</div><span class="footer-heading">BRAND</span><span>Beauty for every day.</span><span>〒819-0022<br>福岡県福岡市西区福重5丁目4-10</span><span>TEL　092-895-2580</span></div><nav class="footer-group"><span class="footer-heading">SALON / SERVICE</span><a href="./index.html">HOME</a><a href="./hair.html">HAIR</a><a href="./nail-eye.html">NAIL &amp; EYE</a><a href="./staff.html">STAFF</a><a href="./salon.html">SALON</a></nav><nav class="footer-group"><span class="footer-heading">RESERVATION</span><a href="./index.html#reservation">ROSE HIP WEB予約</a><a href="tel:0928952580">TEL　092-895-2580</a></nav><div class="footer-group footer-recruit"><span class="footer-heading">RECRUIT</span><a href="./recruit.html">RECRUIT</a><p>スタッフ募集<br>美容を、もっと楽しむ仲間を<br>待っています。</p><a href="./recruit.html">VIEW RECRUIT →</a></div></div><div class="footer-bottom"><span>© ROSE HIP</span><a href="#top">PAGE TOP ↑</a></div>`}if(!document.body.classList.contains('recruit-page')){const c=document.createElement('aside');c.className='recruit-float';c.innerHTML=`<a href="./recruit.html" aria-label="スタッフ募集 採用ページへ"><img class="recruit-float__image" src="./assets/images/recruit/start.jpg" alt=""><span class="recruit-float__body"><span class="recruit-float__eyebrow">RECRUIT</span><span class="recruit-float__title">スタッフ募集</span><span class="recruit-float__copy">美容を、もっと楽しむ仲間を待っています。</span><span class="recruit-float__link">VIEW RECRUIT →</span></span></a><button class="recruit-float__close" type="button" aria-label="スタッフ募集バナーを閉じる">×</button>`;document.body.append(c);c.querySelector('button').addEventListener('click',()=>c.remove())}
if(!document.body.classList.contains('recruit-page')){const floating=document.querySelector('.recruit-float');if(floating){const body=floating.querySelector('.recruit-float__body');const eyebrow=body.querySelector('.recruit-float__eyebrow');const title=body.querySelector('.recruit-float__title');const center=document.createElement('span');center.className='recruit-float-center';center.innerHTML='<span class="recruit-word">スタッフ</span><span class="recruit-word">募集</span><span class="recruit-arrow">→</span>';eyebrow.remove();title.remove();body.prepend(center);floating.querySelector('.recruit-float__close')?.remove();const ring=document.createElementNS('http://www.w3.org/2000/svg','svg');ring.classList.add('recruit-ring');ring.setAttribute('viewBox','0 0 104 104');ring.setAttribute('aria-hidden','true');ring.innerHTML='<defs><path id="recruit-ring-path" d="M 52,52 m -45,0 a 45,45 0 1,1 90,0 a 45,45 0 1,1 -90,0"/></defs><text><textPath href="#recruit-ring-path" startOffset="0%">WE\'RE HIRING ・ ROSE HIP ・ WE\'RE HIRING ・</textPath></text>';body.append(ring)}if(footerObserverTarget&&floating){new IntersectionObserver(entries=>floating.classList.toggle('is-footer-visible',entries[0].isIntersecting),{threshold:.08}).observe(footerObserverTarget)}}
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const slot=(title,note)=>`<div class="photo-placeholder"><div class="photo-placeholder__copy"><span class="photo-placeholder__title">${title}</span><span class="photo-placeholder__note">${note}</span></div></div>`;const gallery=(className,title,note,count)=>`<div class="generated-gallery ${className}" aria-label="${note}">${Array.from({length:count},()=>slot(title,note)).join('')}</div>`;
const beautyPage=document.body.classList.contains('beauty-page');document.querySelectorAll('.visual-placeholder').forEach(el=>{const eye=el.classList.contains('eye-visual');const label=eye?'EYE':'NAIL';const note=eye?'目元仕上がり写真':'ネイル仕上がり写真';const numberedGallery=Array.from({length:3},(_,index)=>slot(`${label}<br>${eye?String(index+1).padStart(2,'0'):`PHOTO ${String(index+1).padStart(2,'0')}`}`,note)).join('');el.outerHTML=beautyPage?`<div class="generated-gallery ${eye?'eye-gallery':'nail-gallery'}" aria-label="${note}">${numberedGallery}</div>`:gallery(eye?'eye-gallery':'nail-gallery',eye?'EYE PHOTO':'NAIL PHOTO',eye?'目元デザイン':'ネイルデザイン',3)});
if(!window.matchMedia('(max-width:850px)').matches){const center=document.querySelector('.recruit-float-center');if(center&&!center.querySelector('.recruit-float__eyebrow')){const label=document.createElement('span');label.className='recruit-float__eyebrow';label.textContent='RECRUIT';center.prepend(label)}}
const reservationFooterGroup=footer?.querySelectorAll('.footer-group')[2];if(reservationFooterGroup&&!reservationFooterGroup.querySelector('a[href*="hotpepper"]')){const hot=document.createElement('a');hot.href='https://beauty.hotpepper.jp/slnH000067615/';hot.target='_blank';hot.rel='noopener';hot.textContent='HOT PEPPER BEAUTY';reservationFooterGroup.insertBefore(hot,reservationFooterGroup.querySelector('a'))}

document.querySelectorAll('.nav-dropdown').forEach(dropdown=>{const toggle=dropdown.querySelector('.nav-dropdown-toggle');const menu=dropdown.querySelector('.nav-dropdown-menu');const close=()=>{toggle.setAttribute('aria-expanded','false');dropdown.classList.remove('open')};toggle.addEventListener('click',event=>{event.stopPropagation();const open=toggle.getAttribute('aria-expanded')==='true';document.querySelectorAll('.nav-dropdown').forEach(other=>{other.querySelector('.nav-dropdown-toggle')?.setAttribute('aria-expanded','false');other.classList.remove('open')});if(!open){toggle.setAttribute('aria-expanded','true');dropdown.classList.add('open')}});toggle.addEventListener('keydown',event=>{if(event.key==='ArrowDown'||event.key==='Enter'||event.key===' '){event.preventDefault();toggle.click();menu.querySelector('a')?.focus()}if(event.key==='Escape')close()});menu.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close();toggle.focus()}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const links=[...menu.querySelectorAll('a')];const next=links[(links.indexOf(document.activeElement)+(event.key==='ArrowDown'?1:links.length-1))%links.length];next.focus()}});document.addEventListener('click',event=>{if(!dropdown.contains(event.target))close()})});
if(footer){const serviceNav=footer.querySelectorAll('.footer-group')[1];if(serviceNav){serviceNav.querySelector('.footer-heading').textContent='サロン / サービス';const links=[...serviceNav.querySelectorAll('a')];const labels=['ホーム','ヘア','ネイル＆アイ','スタッフ','サロン'];links.forEach((link,index)=>{if(labels[index])link.textContent=labels[index]});const fee=document.createElement('span');fee.className='footer-nav-heading';fee.textContent='料金';const hair=links.find(link=>link.getAttribute('href')?.endsWith('hair.html'));const nail=links.find(link=>link.getAttribute('href')?.endsWith('nail-eye.html'));if(hair&&nail){fee.className='footer-heading footer-fee-heading';serviceNav.insertBefore(fee,hair);hair.classList.add('footer-fee-link');nail.classList.add('footer-fee-link')}}const recruitGroup=footer.querySelector('.footer-recruit');if(recruitGroup){const heading=recruitGroup.querySelector('.footer-heading');if(heading)heading.textContent='スタッフ募集';const link=recruitGroup.querySelector('a');if(link)link.textContent='スタッフ募集'}}
document.querySelectorAll('.site-header .reserve-link,.site-header .mobile-reserve,.mobile-menu a[href="#reservation"]').forEach(link=>{if(!document.body.classList.contains('reserve-page'))link.href='./reserve.html'});
document.querySelectorAll('.recruit-actions a[href="#reservation"],section[id="reservation"] a[href*="#reservation"]').forEach(link=>{if(!document.body.classList.contains('recruit-page'))link.href='./reserve.html'});
document.querySelectorAll('.footer a').forEach(link=>{if(link.textContent.includes('ROSE HIP WEB予約'))link.href='https://rosehip.plus2.vc/sprsv/contents_select.php';});
document.querySelectorAll('[data-contact-form]').forEach(form=>{const endpoint=form.dataset.endpoint?.trim();const status=form.querySelector('.form-status');const button=form.querySelector('button[type="submit"]');if(!endpoint){form.addEventListener('submit',event=>{event.preventDefault();if(status)status.textContent='送信機能は本番環境接続後に有効になります。';});return}form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;button.disabled=true;if(status)status.textContent='送信中…';try{const response=await fetch(endpoint,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});const result=await response.json().catch(()=>({}));if(!response.ok||result.success!==true)throw new Error('request failed');form.reset();if(status)status.textContent='送信が完了しました';}catch(error){if(status)status.textContent='送信できませんでした。時間をおいて再度お試しください。';}finally{button.disabled=false}})});
